language: node_js
node_js: node
deploy: https://ancient-sierra-81783.herokuapp.com/
  provider: heroku
  api_key:
    secure: ZKtjxhO9n0340E04Or0y3Fgm98Zx/if+rxstxDw5B9uAGtbQPXd7pbA8QGm++gvi7cm5chpug2kGIiAO4nGeu52atr+IrTdtCBC/OFn3hjL8UB8759pQlkOhGIJE1wOiozj2tY4Am6w66CSNvo3LKkwU7qLyQasAZKAR/+BG9yL5+Pl9iIGZmiaPM93M3A2Jheqp/CJ0bbmrpV26ZpuImdLDwPV2yB970BcFPxbuHn47u5AcUj4hrOpViBmJt1thYKD8qbltKp136vbUrtOvTT+6SjhomfcnlMyu+pgqd5kBlDVzZZRKsp4F91XAT2Pxm36xXj6fXPkbQLoaLolIKp+TCIRaUuezy8UBn+djFmeplS9wow7C2kxLMgbVOmUzpTHBrDI+sORrSaBoQXcA1AegBJW1MxOP/gQ0kOsqcYj0DMweOL66+2fvkGR/7neZm147wfObFfPPBpjAPiCZPgzHTE0E4T8d9/rK6YCuAyZU054tM/Q5/RskXuu15Moj+iEdf1dv/c1dQ+vfTujsTyS+decFxS6uW8Jq1L1IyH8RAmKhPszQ1jem+kjj1qqnGUn95WB4nsnbs7nUpc1Q8BfntYLb1vftRGdphefH70YtZfG5iIOaA/bXIeW6KfnTgAs7+kJ70+qUtWuJwDGh3Vj4ALLEktwncbTYQ1y7mZ4=
  app: node-shopping-list-integration-tests
  on:
    repo: Reyesjunk/node-shopping-list-integration-tests
